const TRENDING_DATA = [
  {
    image: '/assets/images/trending/t1.jpeg',
    imageAlt: '',
    title: 'Soulection',
    value: '135 ETH',
    slug: 'soulection',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 230 others',
  },
  {
    image: '/assets/images/trending/t2.png',
    imageAlt: '',
    title: 'Warp Records',
    value: '2,530 ETH',
    slug: 'warp',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 6,480 others',
  },
  {
    image: '/assets/images/trending/t3.png',
    imageAlt: '',
    title: 'Trance Party',
    value: '180 ETH',
    slug: 'trance',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 380 others',
  },
  {
    image: '/assets/images/trending/t4.jpeg',
    imageAlt: '',
    title: 'Ezra Collective',
    value: '22 ETH',
    slug: 'ezra',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 125 others',
  },
  {
    image: '/assets/images/trending/t5.png',
    imageAlt: '',
    title: 'NVSHU',
    value: '58 ETH',
    slug: 'nvshu',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 230 others',
  },
  {
    image: '/assets/images/trending/t6.jpeg',
    imageAlt: '',
    title: 'CHAOS',
    value: '856 ETH',
    slug: 'chaos',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+ 77 others',
  },
]

export default TRENDING_DATA
