const COMMUNITIES_DATA = [
  {
    image: '/assets/images/explore/e1.jpeg',
    imageAlt: '',
    title: 'PC Music Club',
    value: '2,435 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+3,304 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e2.png',
    imageAlt: '',
    title: 'Alfa Mist',
    value: '12 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+500 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e3.jpeg',
    imageAlt: '',
    title: 'Soulection',
    value: '25 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+230 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e4.png',
    imageAlt: '',
    title: 'Warp Records',
    value: '5,654 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+5,003 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e5.png',
    imageAlt: '',
    title: 'NVSHU',
    value: '2,530 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+30 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e6.jpeg',
    imageAlt: '',
    title: 'Boiler Room',
    value: '45,065 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+13,450 others',
    type: 'trending',
  },
  {
    image: '/assets/images/explore/e7.png',
    imageAlt: '',
    title: 'Trance Party',
    value: '0.4 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+30 others',
    type: 'new',
  },
  {
    image: '/assets/images/explore/e8.jpeg',
    imageAlt: '',
    title: 'Ezra Collective',
    value: '1.3 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+18 others',
    type: 'new',
  },
  {
    image: '/assets/images/explore/e9.jpeg',
    imageAlt: '',
    title: 'Luna Li',
    value: '0.43 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+19 others',
    type: 'new',
  },
  {
    image: '/assets/images/explore/e10.jpeg',
    imageAlt: '',
    title: 'Touching Bass',
    value: '2.65 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+65 others',
    type: 'new',
  },
  {
    image: '/assets/images/explore/e11.jpeg',
    imageAlt: '',
    title: 'CHAOS',
    value: '120 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+77 others',
    type: 'new',
  },
  {
    image: '/assets/images/explore/e12.jpeg',
    imageAlt: '',
    title: 'TheLot Radio',
    value: '53 ETH',
    href: '#',
    users: [
      '/assets/images/users/u1.jpeg',
      '/assets/images/users/u2.jpeg',
      '/assets/images/users/u3.jpeg',
      '/assets/images/users/u4.jpeg',
    ],
    text: '+326 others',
    type: 'new',
  },
]

export default COMMUNITIES_DATA
